-- ─────────────────────────────────────────────────────────────────────────────
-- Valoryx — PostgreSQL / Supabase schema (production blueprint)
--
-- Architecture notes:
--   • Row Level Security isolates every tenant's data by auth.uid().
--   • The analysis pipeline (Edge Function) writes immutable `analyses` rows;
--     the latest analysis per company powers the result screen.
--   • Designed to scale to 100k+ users: heavy JSONB payloads for AI output,
--     normalized tables for the entities that drive queries (watchlist, alerts).
-- ─────────────────────────────────────────────────────────────────────────────

create extension if not exists "pgcrypto";

-- ── Subscription tiers ───────────────────────────────────────────────────────
create type plan_tier as enum ('starter', 'pro', 'investor');
create type verdict as enum ('excellent', 'good', 'neutral', 'high-risk', 'avoid');
create type alert_type as enum ('funding', 'results', 'risk', 'score');

-- ── Profiles (1:1 with auth.users) ───────────────────────────────────────────
create table profiles (
  id            uuid primary key references auth.users on delete cascade,
  full_name     text,
  company_name  text,
  plan          plan_tier not null default 'starter',
  analyses_used integer   not null default 0,
  created_at    timestamptz not null default now()
);

-- Monthly quota per tier, enforced in the Edge Function before an analysis runs.
create table plan_limits (
  plan            plan_tier primary key,
  monthly_quota   integer not null,      -- -1 = unlimited
  max_watchlists  integer not null,
  pdf_export      boolean not null,
  ai_alerts       boolean not null,
  advanced_valuation boolean not null
);
insert into plan_limits values
  ('starter',  10,  1, false, false, false),
  ('pro',      100, 5, true,  true,  false),
  ('investor', -1, -1, true,  true,  true);

-- ── Companies (deduplicated by SIREN where available) ────────────────────────
create table companies (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  siren       text unique,
  website     text,
  linkedin    text,
  sector      text,
  location    text,
  stage       text,            -- 'Private' | 'Public'
  logo        text,
  founded     integer,
  headcount   integer,
  created_at  timestamptz not null default now()
);
create index on companies using gin (to_tsvector('french', name || ' ' || coalesce(sector, '')));

-- ── Analyses (immutable; one per pipeline run) ───────────────────────────────
-- The full AI output (criteria, summary, financials, competitors…) is stored as
-- JSONB so the schema can evolve without migrations, while the columns we filter
-- and sort on are promoted to real columns + indexes.
create table analyses (
  id            uuid primary key default gen_random_uuid(),
  company_id    uuid not null references companies on delete cascade,
  requested_by  uuid references profiles on delete set null,
  score         integer not null check (score between 0 and 100),
  verdict       verdict not null,
  revenue       numeric,         -- €M, latest year
  revenue_growth numeric,        -- %
  ebitda_margin numeric,
  net_margin    numeric,
  valuation     numeric,         -- €M
  payload       jsonb not null,  -- { summary, criteria[], financials[], competitors[], funding[], management[] }
  model_version text not null default 'valoryx-score-v1',
  created_at    timestamptz not null default now()
);
create index on analyses (company_id, created_at desc);
create index on analyses (score desc);

-- ── Watchlist ────────────────────────────────────────────────────────────────
create table watchlist_items (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references profiles on delete cascade,
  company_id  uuid not null references companies on delete cascade,
  created_at  timestamptz not null default now(),
  unique (user_id, company_id)
);

-- ── Favorites ────────────────────────────────────────────────────────────────
create table favorites (
  user_id     uuid not null references profiles on delete cascade,
  company_id  uuid not null references companies on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, company_id)
);

-- ── Alerts (generated by the monitoring job) ─────────────────────────────────
create table alerts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references profiles on delete cascade,
  company_id  uuid not null references companies on delete cascade,
  type        alert_type not null,
  title       text not null,
  detail      text,
  tone        text not null default 'neutral',  -- positive | negative | neutral
  read        boolean not null default false,
  created_at  timestamptz not null default now()
);
create index on alerts (user_id, read, created_at desc);

-- ── Row Level Security ───────────────────────────────────────────────────────
alter table profiles        enable row level security;
alter table watchlist_items enable row level security;
alter table favorites       enable row level security;
alter table alerts          enable row level security;

create policy "own profile"   on profiles        for all using (id = auth.uid());
create policy "own watchlist" on watchlist_items for all using (user_id = auth.uid());
create policy "own favorites" on favorites        for all using (user_id = auth.uid());
create policy "own alerts"    on alerts            for all using (user_id = auth.uid());

-- Companies & analyses are readable by any authenticated user (shared intelligence),
-- but only the pipeline (service role) may write them.
alter table companies enable row level security;
alter table analyses  enable row level security;
create policy "read companies" on companies for select using (auth.role() = 'authenticated');
create policy "read analyses"  on analyses  for select using (auth.role() = 'authenticated');

-- ── Report cache (used by the running app) ───────────────────────────────────
-- A JSON snapshot of each generated analysis, keyed by external id (SIREN /
-- ticker / slug). The fully-normalized `analyses` table above is the production
-- warehouse; this cache is what the result page reads for instant rendering.
create table reports (
  external_id text primary key,
  company     jsonb not null,
  mode        text  not null default 'live',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
alter table reports enable row level security;
create policy "read reports" on reports for select using (true);
-- Writes are performed by the pipeline using the service role (bypasses RLS).

-- ── Auto-provision a profile on signup ───────────────────────────────────────
create or replace function handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, full_name) values (new.id, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();
